# Generated by Django 3.1.7 on 2021-02-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', '1 class'), ('2', '2 class'), ('3', '3 class'), ('4', '4 class'), ('5', '5 class'), ('6', '6 class'), ('7', '7 class'), ('8', '8 class'), ('9', '9 class'), ('10', '10th class')], default='....', max_length=256),
        ),
    ]
