# Generated by Django 3.1.7 on 2021-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'DEV'), (2, 'PROD'), (3, 'LIVE'), (4, 'CLOSED')], default=0),
        ),
    ]
