# Generated by Django 3.1.7 on 2021-02-26 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210226_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('gender', models.BooleanField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Trans')], default='1')),
                ('adhar', models.IntegerField(blank=True, null=True)),
                ('father_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=256, null=True)),
                ('student_class', models.CharField(choices=[('1', '1 class'), ('2', '2 class'), ('3', '3 class'), ('4', '4 class'), ('5', '5 class'), ('6', '6 class'), ('7', '7 class'), ('8', '8 class'), ('9', '9 class'), ('10', '10th class')], default='1', max_length=256)),
                ('student_section', models.CharField(blank=True, max_length=50, null=True)),
                ('fav_language', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
