# Generated by Django 3.1.7 on 2021-02-28 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Professor'), ('3', 'lower_staf')], default='1', max_length=256),
        ),
    ]
