# Generated by Django 3.1.7 on 2021-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210228_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addr',
            field=models.TextField(blank=True, default='Home'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=256),
        ),
    ]
