# Generated by Django 3.1.7 on 2021-03-17 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0002_department_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=256, unique=True)),
                ('class_name', models.CharField(max_length=256)),
                ('client', models.CharField(max_length=256)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'None'), (1, 'DEV'), (2, 'PROD'), (3, 'LIVE'), (4, 'CLOSED')], default=0)),
                ('class_year', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='hod',
        ),
        migrations.AddField(
            model_name='department',
            name='start',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'DEV'), (2, 'PROD'), (3, 'LIVE'), (4, 'CLOSED')], default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.SmallIntegerField(choices=[(0, 'None'), (1, 'PRINCIPLE'), (2, 'HOD'), (2, 'PROFESSOR'), (3, 'ASST-PROFESSOR'), (4, 'ASSOCIAT-PROFESSOR'), (5, 'LAB-INCHARGE'), (6, 'LAB-ASSISTANT')], default=0)),
                ('start', models.DateField(auto_now_add=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.classes')),
                ('professor', models.ForeignKey(limit_choices_to={'type': 2}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
