# Generated by Django 3.1.7 on 2021-03-17 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departments', '0003_auto_20210317_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='client',
        ),
        migrations.AddField(
            model_name='classes',
            name='professor',
            field=models.ForeignKey(limit_choices_to={'type': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
